/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Sat Feb 14 11:27:49 JST 2015
* Mission file name: RHS_CO10_Burden_the_Grieves_1_2.Chernarus
* Mission name: RHS_CO10_Burden_the_Grieves_1_2.Chernarus
* Required mods:
* + ArmA 3
* + RHS USAF
* + TFAR
* 
* Call the script: _dummy = [] execvm "lea\loadoutServer.sqf";
* 
*/

/**
* Loadout for crates
*/

//No named crates in this mission.

/**
* Loadout for soldiers units
*/

if (!isNil "unit_0_0") then {
removeallweapons unit_0_0;
removeallassigneditems unit_0_0;
removeBackpack unit_0_0;
removeVest unit_0_0;
removeHeadgear unit_0_0;
removeUniform unit_0_0;
removeGoggles unit_0_0;

unit_0_0 addWeapon "ItemMap";
unit_0_0 addWeapon "ItemWatch";
unit_0_0 addWeapon "ItemCompass";
unit_0_0 addWeapon "rhsusf_ach_helmet_ocp";
unit_0_0 addWeapon "rhsusf_ANPVS_15";
unit_0_0 addWeapon "Binocular";
unit_0_0 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_0_0) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_0_0 addWeapon "rhs_m4a1_m320";
removeBackpack unit_0_0;
unit_0_0 addPrimaryWeaponItem "acc_pointer_IR";
unit_0_0 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_0_0 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_0_0);
clearMagazineCargoGlobal (backpackContainer unit_0_0);
clearWeaponCargoGlobal (backpackContainer unit_0_0);
(backpackContainer unit_0_0) addmagazinecargoGlobal ["3Rnd_SmokeGreen_Grenade_shell",2];
(backpackContainer unit_0_0) addmagazinecargoGlobal ["3Rnd_SmokeRed_Grenade_shell",2];
(backpackContainer unit_0_0) addmagazinecargoGlobal ["3Rnd_SmokeBlue_Grenade_shell",2];
unit_0_0 addItemToBackpack "SmokeShell";
unit_0_0 addItemToBackpack "SmokeShell";
unit_0_0 addItemToBackpack "SmokeShell";
unit_0_0 addItemToBackpack "SmokeShell";
unit_0_0 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_0_0);
clearMagazineCargoGlobal (vestContainer unit_0_0);
clearWeaponCargoGlobal (vestContainer unit_0_0);
(vestContainer unit_0_0) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_0_0 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_0_0);
clearMagazineCargoGlobal (uniformContainer unit_0_0);
clearWeaponCargoGlobal (uniformContainer unit_0_0);
(uniformContainer unit_0_0) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_0_0 addWeapon "tf_anprc152";
unit_0_0 selectWeapon (primaryWeapon unit_0_0);
};

if (!isNil "unit_0_1") then {
removeallweapons unit_0_1;
removeallassigneditems unit_0_1;
removeBackpack unit_0_1;
removeVest unit_0_1;
removeHeadgear unit_0_1;
removeUniform unit_0_1;
removeGoggles unit_0_1;

unit_0_1 addWeapon "ItemMap";
unit_0_1 addWeapon "ItemWatch";
unit_0_1 addWeapon "ItemCompass";
unit_0_1 addWeapon "rhsusf_ach_helmet_ocp";
unit_0_1 addWeapon "rhsusf_ANPVS_15";
unit_0_1 addWeapon "Binocular";
unit_0_1 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_0_1) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_0_1 addWeapon "rhs_m4a1_m320";
removeBackpack unit_0_1;
unit_0_1 addPrimaryWeaponItem "acc_pointer_IR";
unit_0_1 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_0_1 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_0_1);
clearMagazineCargoGlobal (backpackContainer unit_0_1);
clearWeaponCargoGlobal (backpackContainer unit_0_1);
(backpackContainer unit_0_1) addmagazinecargoGlobal ["3Rnd_SmokeGreen_Grenade_shell",2];
(backpackContainer unit_0_1) addmagazinecargoGlobal ["3Rnd_SmokeRed_Grenade_shell",2];
(backpackContainer unit_0_1) addmagazinecargoGlobal ["3Rnd_SmokeBlue_Grenade_shell",2];
unit_0_1 addItemToBackpack "SmokeShell";
unit_0_1 addItemToBackpack "SmokeShell";
unit_0_1 addItemToBackpack "SmokeShell";
unit_0_1 addItemToBackpack "SmokeShell";
unit_0_1 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_0_1);
clearMagazineCargoGlobal (vestContainer unit_0_1);
clearWeaponCargoGlobal (vestContainer unit_0_1);
(vestContainer unit_0_1) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_0_1 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_0_1);
clearMagazineCargoGlobal (uniformContainer unit_0_1);
clearWeaponCargoGlobal (uniformContainer unit_0_1);
(uniformContainer unit_0_1) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_0_1 addWeapon "tf_anprc152";
unit_0_1 selectWeapon (primaryWeapon unit_0_1);
};

if (!isNil "unit_6_7") then {
removeallweapons unit_6_7;
removeallassigneditems unit_6_7;
removeBackpack unit_6_7;
removeVest unit_6_7;
removeHeadgear unit_6_7;
removeUniform unit_6_7;
removeGoggles unit_6_7;

unit_6_7 addWeapon "ItemMap";
unit_6_7 addWeapon "ItemWatch";
unit_6_7 addWeapon "ItemCompass";
unit_6_7 addWeapon "rhsusf_ach_helmet_ocp";
unit_6_7 addWeapon "rhsusf_ANPVS_15";
unit_6_7 addWeapon "Binocular";
unit_6_7 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_6_7) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_6_7 addWeapon "rhs_m4a1_m320";
removeBackpack unit_6_7;
unit_6_7 addPrimaryWeaponItem "acc_pointer_IR";
unit_6_7 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_6_7 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_6_7);
clearMagazineCargoGlobal (backpackContainer unit_6_7);
clearWeaponCargoGlobal (backpackContainer unit_6_7);
(backpackContainer unit_6_7) addmagazinecargoGlobal ["3Rnd_SmokeGreen_Grenade_shell",2];
(backpackContainer unit_6_7) addmagazinecargoGlobal ["3Rnd_SmokeRed_Grenade_shell",2];
(backpackContainer unit_6_7) addmagazinecargoGlobal ["3Rnd_SmokeBlue_Grenade_shell",2];
unit_6_7 addItemToBackpack "SmokeShell";
unit_6_7 addItemToBackpack "SmokeShell";
unit_6_7 addItemToBackpack "SmokeShell";
unit_6_7 addItemToBackpack "SmokeShell";
unit_6_7 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_6_7);
clearMagazineCargoGlobal (vestContainer unit_6_7);
clearWeaponCargoGlobal (vestContainer unit_6_7);
(vestContainer unit_6_7) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_6_7 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_6_7);
clearMagazineCargoGlobal (uniformContainer unit_6_7);
clearWeaponCargoGlobal (uniformContainer unit_6_7);
(uniformContainer unit_6_7) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_6_7 addWeapon "tf_anprc152";
unit_6_7 selectWeapon (primaryWeapon unit_6_7);
};

if (!isNil "unit_6_8") then {
removeallweapons unit_6_8;
removeallassigneditems unit_6_8;
removeBackpack unit_6_8;
removeVest unit_6_8;
removeHeadgear unit_6_8;
removeUniform unit_6_8;
removeGoggles unit_6_8;

unit_6_8 addWeapon "ItemMap";
unit_6_8 addWeapon "ItemWatch";
unit_6_8 addWeapon "ItemCompass";
unit_6_8 addWeapon "rhsusf_ach_helmet_ocp";
unit_6_8 addWeapon "rhsusf_ANPVS_15";
unit_6_8 addWeapon "Binocular";
unit_6_8 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_6_8) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_6_8 addWeapon "rhs_m4a1_m320";
removeBackpack unit_6_8;
unit_6_8 addPrimaryWeaponItem "acc_pointer_IR";
unit_6_8 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_6_8 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_6_8);
clearMagazineCargoGlobal (backpackContainer unit_6_8);
clearWeaponCargoGlobal (backpackContainer unit_6_8);
(backpackContainer unit_6_8) addmagazinecargoGlobal ["3Rnd_SmokeGreen_Grenade_shell",2];
(backpackContainer unit_6_8) addmagazinecargoGlobal ["3Rnd_SmokeRed_Grenade_shell",2];
(backpackContainer unit_6_8) addmagazinecargoGlobal ["3Rnd_SmokeBlue_Grenade_shell",2];
unit_6_8 addItemToBackpack "SmokeShell";
unit_6_8 addItemToBackpack "SmokeShell";
unit_6_8 addItemToBackpack "SmokeShell";
unit_6_8 addItemToBackpack "SmokeShell";
unit_6_8 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_6_8);
clearMagazineCargoGlobal (vestContainer unit_6_8);
clearWeaponCargoGlobal (vestContainer unit_6_8);
(vestContainer unit_6_8) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_6_8 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_6_8);
clearMagazineCargoGlobal (uniformContainer unit_6_8);
clearWeaponCargoGlobal (uniformContainer unit_6_8);
(uniformContainer unit_6_8) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_6_8 addWeapon "tf_anprc152";
unit_6_8 selectWeapon (primaryWeapon unit_6_8);
};

if (!isNil "unit_6_9") then {
removeallweapons unit_6_9;
removeallassigneditems unit_6_9;
removeBackpack unit_6_9;
removeVest unit_6_9;
removeHeadgear unit_6_9;
removeUniform unit_6_9;
removeGoggles unit_6_9;

unit_6_9 addWeapon "ItemMap";
unit_6_9 addWeapon "ItemWatch";
unit_6_9 addWeapon "ItemCompass";
unit_6_9 addWeapon "rhsusf_ach_helmet_ocp";
unit_6_9 addWeapon "rhsusf_ANPVS_15";
unit_6_9 addWeapon "Binocular";
unit_6_9 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_6_9) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",1];
unit_6_9 addWeapon "rhs_weap_m240B";
removeBackpack unit_6_9;
unit_6_9 addPrimaryWeaponItem "acc_pointer_IR";
unit_6_9 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_6_9 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_6_9);
clearMagazineCargoGlobal (backpackContainer unit_6_9);
clearWeaponCargoGlobal (backpackContainer unit_6_9);
(backpackContainer unit_6_9) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_6_9 addItemToBackpack "SmokeShell";
unit_6_9 addItemToBackpack "SmokeShell";
unit_6_9 addItemToBackpack "SmokeShell";
unit_6_9 addItemToBackpack "SmokeShell";
unit_6_9 addItemToBackpack "rhs_mag_m67";
unit_6_9 addItemToBackpack "rhs_mag_m67";
unit_6_9 addItemToBackpack "rhs_mag_m67";
unit_6_9 addItemToBackpack "rhs_mag_m67";
unit_6_9 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_6_9);
clearMagazineCargoGlobal (vestContainer unit_6_9);
clearWeaponCargoGlobal (vestContainer unit_6_9);
(vestContainer unit_6_9) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_6_9 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_6_9);
clearMagazineCargoGlobal (uniformContainer unit_6_9);
clearWeaponCargoGlobal (uniformContainer unit_6_9);
unit_6_9 addWeapon "tf_anprc152";
unit_6_9 selectWeapon (primaryWeapon unit_6_9);
};

if (!isNil "unit_6_10") then {
removeallweapons unit_6_10;
removeallassigneditems unit_6_10;
removeBackpack unit_6_10;
removeVest unit_6_10;
removeHeadgear unit_6_10;
removeUniform unit_6_10;
removeGoggles unit_6_10;

unit_6_10 addWeapon "ItemMap";
unit_6_10 addWeapon "ItemWatch";
unit_6_10 addWeapon "ItemCompass";
unit_6_10 addWeapon "rhsusf_ach_helmet_ocp";
unit_6_10 addWeapon "rhsusf_ANPVS_15";
unit_6_10 addWeapon "Binocular";
unit_6_10 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_6_10) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_6_10 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_6_10;
unit_6_10 addPrimaryWeaponItem "acc_pointer_IR";
unit_6_10 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_6_10 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_6_10);
clearMagazineCargoGlobal (backpackContainer unit_6_10);
clearWeaponCargoGlobal (backpackContainer unit_6_10);
(backpackContainer unit_6_10) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_6_10 addItemToBackpack "SmokeShell";
unit_6_10 addItemToBackpack "SmokeShell";
unit_6_10 addItemToBackpack "SmokeShell";
unit_6_10 addItemToBackpack "SmokeShell";
unit_6_10 addItemToBackpack "rhs_mag_m67";
unit_6_10 addItemToBackpack "rhs_mag_m67";
unit_6_10 addItemToBackpack "rhs_mag_m67";
unit_6_10 addItemToBackpack "rhs_mag_m67";
unit_6_10 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_6_10);
clearMagazineCargoGlobal (vestContainer unit_6_10);
clearWeaponCargoGlobal (vestContainer unit_6_10);
(vestContainer unit_6_10) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_6_10 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_6_10);
clearMagazineCargoGlobal (uniformContainer unit_6_10);
clearWeaponCargoGlobal (uniformContainer unit_6_10);
(uniformContainer unit_6_10) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_6_10 addWeapon "tf_anprc152";
unit_6_10 selectWeapon (primaryWeapon unit_6_10);
};

if (!isNil "unit_6_11") then {
removeallweapons unit_6_11;
removeallassigneditems unit_6_11;
removeBackpack unit_6_11;
removeVest unit_6_11;
removeHeadgear unit_6_11;
removeUniform unit_6_11;
removeGoggles unit_6_11;

unit_6_11 addWeapon "ItemMap";
unit_6_11 addWeapon "ItemWatch";
unit_6_11 addWeapon "ItemCompass";
unit_6_11 addWeapon "rhsusf_ach_helmet_ocp";
unit_6_11 addWeapon "rhsusf_ANPVS_15";
unit_6_11 addWeapon "Binocular";
unit_6_11 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_6_11) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_6_11 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_6_11;
unit_6_11 addPrimaryWeaponItem "acc_pointer_IR";
unit_6_11 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_6_11 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_6_11) addmagazinecargoGlobal ["rhs_fgm148_magazine_AT",1];
unit_6_11 addWeapon "rhs_weap_fgm148";
removeBackpack unit_6_11;
unit_6_11 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_6_11);
clearMagazineCargoGlobal (backpackContainer unit_6_11);
clearWeaponCargoGlobal (backpackContainer unit_6_11);
(backpackContainer unit_6_11) addmagazinecargoGlobal ["rhs_fgm148_magazine_AT",2];
unit_6_11 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_6_11);
clearMagazineCargoGlobal (vestContainer unit_6_11);
clearWeaponCargoGlobal (vestContainer unit_6_11);
(vestContainer unit_6_11) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_6_11 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_6_11);
clearMagazineCargoGlobal (uniformContainer unit_6_11);
clearWeaponCargoGlobal (uniformContainer unit_6_11);
(uniformContainer unit_6_11) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_6_11 addWeapon "tf_anprc152";
unit_6_11 selectWeapon (primaryWeapon unit_6_11);
};

if (!isNil "unit_6_12") then {
removeallweapons unit_6_12;
removeallassigneditems unit_6_12;
removeBackpack unit_6_12;
removeVest unit_6_12;
removeHeadgear unit_6_12;
removeUniform unit_6_12;
removeGoggles unit_6_12;

unit_6_12 addWeapon "ItemMap";
unit_6_12 addWeapon "ItemWatch";
unit_6_12 addWeapon "ItemCompass";
unit_6_12 addWeapon "rhsusf_ach_helmet_ocp";
unit_6_12 addWeapon "rhsusf_ANPVS_15";
unit_6_12 addWeapon "Binocular";
unit_6_12 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_6_12) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_6_12 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_6_12;
unit_6_12 addPrimaryWeaponItem "acc_pointer_IR";
unit_6_12 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_6_12 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_6_12);
clearMagazineCargoGlobal (backpackContainer unit_6_12);
clearWeaponCargoGlobal (backpackContainer unit_6_12);
(backpackContainer unit_6_12) addmagazinecargoGlobal ["rhs_fgm148_magazine_AT",2];
unit_6_12 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_6_12);
clearMagazineCargoGlobal (vestContainer unit_6_12);
clearWeaponCargoGlobal (vestContainer unit_6_12);
(vestContainer unit_6_12) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_6_12 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_6_12);
clearMagazineCargoGlobal (uniformContainer unit_6_12);
clearWeaponCargoGlobal (uniformContainer unit_6_12);
(uniformContainer unit_6_12) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_6_12 addWeapon "tf_anprc152";
unit_6_12 selectWeapon (primaryWeapon unit_6_12);
};

if (!isNil "unit_6_13") then {
removeallweapons unit_6_13;
removeallassigneditems unit_6_13;
removeBackpack unit_6_13;
removeVest unit_6_13;
removeHeadgear unit_6_13;
removeUniform unit_6_13;
removeGoggles unit_6_13;

unit_6_13 addWeapon "ItemMap";
unit_6_13 addWeapon "ItemWatch";
unit_6_13 addWeapon "ItemCompass";
unit_6_13 addWeapon "rhsusf_ach_helmet_ocp";
unit_6_13 addWeapon "rhsusf_ANPVS_15";
unit_6_13 addWeapon "Binocular";
unit_6_13 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_6_13) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_6_13 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_6_13;
unit_6_13 addPrimaryWeaponItem "acc_pointer_IR";
unit_6_13 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_6_13 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_6_13);
clearMagazineCargoGlobal (backpackContainer unit_6_13);
clearWeaponCargoGlobal (backpackContainer unit_6_13);
unit_6_13 addItemToBackpack "SmokeShell";
unit_6_13 addItemToBackpack "SmokeShell";
unit_6_13 addItemToBackpack "SmokeShell";
unit_6_13 addItemToBackpack "SmokeShell";
unit_6_13 addItemToBackpack "rhs_mag_m67";
unit_6_13 addItemToBackpack "rhs_mag_m67";
unit_6_13 addItemToBackpack "rhs_mag_m67";
unit_6_13 addItemToBackpack "rhs_mag_m67";
unit_6_13 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_6_13);
clearMagazineCargoGlobal (vestContainer unit_6_13);
clearWeaponCargoGlobal (vestContainer unit_6_13);
(vestContainer unit_6_13) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_6_13 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_6_13);
clearMagazineCargoGlobal (uniformContainer unit_6_13);
clearWeaponCargoGlobal (uniformContainer unit_6_13);
(uniformContainer unit_6_13) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_6_13 addWeapon "tf_anprc152";
unit_6_13 selectWeapon (primaryWeapon unit_6_13);
};

if (!isNil "unit_6_14") then {
removeallweapons unit_6_14;
removeallassigneditems unit_6_14;
removeBackpack unit_6_14;
removeVest unit_6_14;
removeHeadgear unit_6_14;
removeUniform unit_6_14;
removeGoggles unit_6_14;

unit_6_14 addWeapon "ItemMap";
unit_6_14 addWeapon "ItemWatch";
unit_6_14 addWeapon "ItemCompass";
unit_6_14 addWeapon "rhsusf_ach_helmet_ocp";
unit_6_14 addWeapon "rhsusf_ANPVS_15";
unit_6_14 addWeapon "Binocular";
unit_6_14 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_6_14) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_6_14 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_6_14;
unit_6_14 addPrimaryWeaponItem "acc_pointer_IR";
unit_6_14 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_6_14 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_6_14);
clearMagazineCargoGlobal (backpackContainer unit_6_14);
clearWeaponCargoGlobal (backpackContainer unit_6_14);
unit_6_14 addItemToBackpack "SmokeShell";
unit_6_14 addItemToBackpack "SmokeShell";
unit_6_14 addItemToBackpack "SmokeShell";
unit_6_14 addItemToBackpack "SmokeShell";
unit_6_14 addItemToBackpack "rhs_mag_m67";
unit_6_14 addItemToBackpack "rhs_mag_m67";
unit_6_14 addItemToBackpack "rhs_mag_m67";
unit_6_14 addItemToBackpack "rhs_mag_m67";
unit_6_14 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_6_14);
clearMagazineCargoGlobal (vestContainer unit_6_14);
clearWeaponCargoGlobal (vestContainer unit_6_14);
(vestContainer unit_6_14) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_6_14 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_6_14);
clearMagazineCargoGlobal (uniformContainer unit_6_14);
clearWeaponCargoGlobal (uniformContainer unit_6_14);
(uniformContainer unit_6_14) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_6_14 addWeapon "tf_anprc152";
unit_6_14 selectWeapon (primaryWeapon unit_6_14);
};

