// A2BM W     110
// DO NOT EDIT THIS FILE

waitUntil {!(isNull player)};
waitUntil {player==player};
switch (side player) do
{
case WEST:
{
player createDiaryRecord ["Diary",["GPS System","You can get to know where you are on the map by GPS system."]];

player createDiaryRecord ["Diary",["Gorka","<marker name='Gorka'>Gorka</marker> is a village that lies on your way.<br/>There is under Chedaki's control.Pay attention to pass there.<br/><br/><img image='Gorka.jpg' width='300' height='168'/>"]];

player createDiaryRecord ["Diary",["Main battle front","<marker name='Battlefront_Line'>Main battle front</marker> so far is <marker name='Novy_Sobor'>Novy Sobor</marker> - <marker name='Pop_Ivan'>Pop Ivan</marker> - <marker name='Nadezhdino'>Nadezhdino</marker> line.<br/>Chedaki is concentrating their armored forces on here."]];

player createDiaryRecord ["Diary",["Battle of Chernogorsk","Situation of <marker name='Chernogorsk'>Chernogorsk</marker> is said to extremely hard.<br/>CDF is still struggling but Chedaki has no intention to deliver the city.<br/><br/>Any way,we have no need to die like a dog in there.<br/><img image='Cherno.jpg' width='300' height='168'/>"]];

player createDiaryRecord ["Diary",["Info about Mimosa","<marker name='Bmor1'>Mimosa</marker> is a mortar battery.<br/>They are waiting for firing request.<br/>In modern warfare,artillerymen have to change their position quickly to avoid firing back with enemy anti-arty rader.<br/>but Chedaki can't afford to buy it so Mimosa can have some fun firing to their heart's content.<br/><br/>This battery arming with:<br/>M252 81mm mortar*8<br/>Mk25 MTVR*3<br/><br/><img image='Mimosa.jpg' width='300' height='168'/>"]];

player createDiaryRecord ["Diary",["Info about Hartshorn","<marker name='HQ'>Head quarter</marker> of 27th MEU is rocated near the airfield.<br/>You must report every thing and beg an order every time for them.<br/>Hartshorn contacts with CDF forces.<br/><br/><img image='Hartshorn.jpg' width='300' height='168'/>"]];

player createDiaryRecord ["Diary",["Info about Gustav","The functional unit which organized for Operation Left-hander.<br/><marker name='Bmorinf1'>Gustav</marker> is armed with a number of AT missiles.<br/>Gustav is not armored so this platoon is more defensive than armored and tracked platoon.<br/><br/>This platoon arming with:<br/>FGM-148 Javelin*4<br/>M966 HMMWV with TOW*2<br/>M998 HMMWV*2<br/><br/><img image='Gustav.jpg' width='300' height='168'/>"]];

player createDiaryRecord ["Diary",["Info about Anton","One of infantry units of 27th MEU.This platoon comes from 3rd Battalion 10th Marines(3/10) like <marker name='Bmecinf1'>Ida</marker>.<br/><marker name='Bmecinf2'>Anton</marker> and Ida should communicate with local citizens who won't evacuate to get intelligence.<br/><br/>This platoon arming with:<br/>AAV7A1 *2<br/><br/><img image='Anton.jpg' width='300' height='168'/><br/>"]];

player createDiaryRecord ["Diary",["Info about Ida","One of infantry units of 27th MEU.This platoon comes from 3rd Battalion 10th Marines(3/10).<br/><marker name='Bmecinf1'>Ida</marker> is observing <marker name='Main Battle Front'>battlefront</marker> and in case Chedaki takes action,Ida must hold the front with <marker name='Bmecinf2'>Anton</marker>.<br/><br/>This platoon arming with:<br/>AAV7A1 *2<br/><br/><img image='Ida.jpg' width='300' height='168'/>"]];

player createDiaryRecord ["Diary",["Info about Turquoise","The armored forces of 27th MEU.This platoon comes from 2nd tank battalion.<br/>The role which imposed on <marker name='Barm1'>Turquoise</marker> is lead of Operation Left-hander.<br/><br/>This platoon arming with:<br/>M1A2 TUSK *4<br/>various support vehicles<br/><br/><img image='Turquoise.jpg' width='300' height='186'/>"]];

player createDiaryRecord ["Diary",["Dead end","You can't pass <marker name='dead end'>this point</marker> because of bulky refuse.<br/>No one knows why this trash be here.<br/>Due to war muddle?<br/>Or Chrenarussian are so slovenly?<br/><br/><img image='Dead end.jpg' width='300' height='180'/><br/>"]];

player createDiaryRecord ["Diary",["Support vehicles","You can call support vehicles(repair,refuel,rearm and ambulance) any time via high-command(ctrl+space).<br/><br/><img image='Support.jpg' width='300' height='168'/><br/>"]];

MAG_tskObj0=player createSimpleTask ["Operation Left-hander"];
MAG_tskObj0 setSimpleTaskDescription ["Since the United States stepped into the conflict between CDF and Chedaki,battle line which Chedaki once extended had been pressed back quickly.<br/><br/>But this is not only because USMC is so mighty but because Chedaki's commander decided to retreat and recover their stance immediately.<br/>Therefore,our advance stopped for the present.We are facing well constructed enemy defence line.<br/><br/>In this operation,you the tank platoon Turquoise are ordered to raid into enemy territory by detouring <marker name='Main battle front'>the Main battle front</marker> ,cooperate with mortar battery <marker name='Bmor1'>Mimosa</marker> to destroy enemy saspected <marker name='vehicle depot'>vehicle depot</marker> in Shakhovka.<br/><br/>Our UAV took below picture.<br/><br/><img image='depot.jpg' width='600' height='336'/><br/><br/>In this picture,<marker name='Vehicle depot'>Shakhoka</marker> seems so quiet but there are some nets proper to hide some vehicle.<br/>We need to check this village and in case there is tank depot,we must destroy that tanks.<br/><br/>First,Advance to <marker name='Observe Position'>Observe Position</marker>.<br/>","Operation Left-hander","Operation Left-hander"];
};
case EAST:
{
};
case RESISTANCE:
{
};
case CIVILIAN:
{
};
};
