/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Sat Feb 14 11:22:51 JST 2015
* Mission file name: RHS_CO08_MoonCollision_1_3.Chernarus
* Mission name: RHS_CO08_MoonCollision_1_3.Chernarus
* Required mods:
* + ArmA 3
* + RHS USAF
* + TFAR
* 
* Call the script: _dummy = [] execvm "lea\loadoutSingleplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

//No named crates in this mission.

/**
* Loadout for soldiers units
*/

if (!isNil "unit_3_3") then {
removeallweapons unit_3_3;
removeallassigneditems unit_3_3;
removeBackpack unit_3_3;
removeVest unit_3_3;
removeHeadgear unit_3_3;
removeUniform unit_3_3;
removeGoggles unit_3_3;

unit_3_3 addWeapon "ItemMap";
unit_3_3 addWeapon "ItemWatch";
unit_3_3 addWeapon "ItemCompass";
unit_3_3 addWeapon "rhsusf_ach_helmet_ocp";
unit_3_3 addWeapon "rhsusf_ANPVS_15";
unit_3_3 addWeapon "Binocular";
unit_3_3 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_3_3) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_3_3 addWeapon "rhs_m4a1_m320";
removeBackpack unit_3_3;
unit_3_3 addPrimaryWeaponItem "acc_pointer_IR";
unit_3_3 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_3_3 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_3_3);
clearMagazineCargoGlobal (backpackContainer unit_3_3);
clearWeaponCargoGlobal (backpackContainer unit_3_3);
(backpackContainer unit_3_3) addmagazinecargoGlobal ["3Rnd_SmokeGreen_Grenade_shell",2];
(backpackContainer unit_3_3) addmagazinecargoGlobal ["3Rnd_SmokeRed_Grenade_shell",2];
(backpackContainer unit_3_3) addmagazinecargoGlobal ["3Rnd_SmokeBlue_Grenade_shell",2];
unit_3_3 addItemToBackpack "SmokeShell";
unit_3_3 addItemToBackpack "SmokeShell";
unit_3_3 addItemToBackpack "SmokeShell";
unit_3_3 addItemToBackpack "SmokeShell";
unit_3_3 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_3_3);
clearMagazineCargoGlobal (vestContainer unit_3_3);
clearWeaponCargoGlobal (vestContainer unit_3_3);
(vestContainer unit_3_3) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_3_3 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_3_3);
clearMagazineCargoGlobal (uniformContainer unit_3_3);
clearWeaponCargoGlobal (uniformContainer unit_3_3);
(uniformContainer unit_3_3) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_3_3 addWeapon "tf_anprc152";
unit_3_3 selectWeapon (primaryWeapon unit_3_3);
};

if (!isNil "unit_3_4") then {
removeallweapons unit_3_4;
removeallassigneditems unit_3_4;
removeBackpack unit_3_4;
removeVest unit_3_4;
removeHeadgear unit_3_4;
removeUniform unit_3_4;
removeGoggles unit_3_4;

unit_3_4 addWeapon "ItemMap";
unit_3_4 addWeapon "ItemWatch";
unit_3_4 addWeapon "ItemCompass";
unit_3_4 addWeapon "rhsusf_ach_helmet_ocp";
unit_3_4 addWeapon "rhsusf_ANPVS_15";
unit_3_4 addWeapon "Binocular";
unit_3_4 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_3_4) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",1];
unit_3_4 addWeapon "rhs_weap_m240B";
removeBackpack unit_3_4;
unit_3_4 addPrimaryWeaponItem "acc_pointer_IR";
unit_3_4 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_3_4 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_3_4);
clearMagazineCargoGlobal (backpackContainer unit_3_4);
clearWeaponCargoGlobal (backpackContainer unit_3_4);
(backpackContainer unit_3_4) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_3_4 addItemToBackpack "SmokeShell";
unit_3_4 addItemToBackpack "SmokeShell";
unit_3_4 addItemToBackpack "SmokeShell";
unit_3_4 addItemToBackpack "SmokeShell";
unit_3_4 addItemToBackpack "rhs_mag_m67";
unit_3_4 addItemToBackpack "rhs_mag_m67";
unit_3_4 addItemToBackpack "rhs_mag_m67";
unit_3_4 addItemToBackpack "rhs_mag_m67";
unit_3_4 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_3_4);
clearMagazineCargoGlobal (vestContainer unit_3_4);
clearWeaponCargoGlobal (vestContainer unit_3_4);
(vestContainer unit_3_4) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_3_4 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_3_4);
clearMagazineCargoGlobal (uniformContainer unit_3_4);
clearWeaponCargoGlobal (uniformContainer unit_3_4);
unit_3_4 addWeapon "tf_anprc152";
unit_3_4 selectWeapon (primaryWeapon unit_3_4);
};

if (!isNil "unit_3_5") then {
removeallweapons unit_3_5;
removeallassigneditems unit_3_5;
removeBackpack unit_3_5;
removeVest unit_3_5;
removeHeadgear unit_3_5;
removeUniform unit_3_5;
removeGoggles unit_3_5;

unit_3_5 addWeapon "ItemMap";
unit_3_5 addWeapon "ItemWatch";
unit_3_5 addWeapon "ItemCompass";
unit_3_5 addWeapon "rhsusf_ach_helmet_ocp";
unit_3_5 addWeapon "rhsusf_ANPVS_15";
unit_3_5 addWeapon "Binocular";
unit_3_5 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_3_5) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_3_5 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_3_5;
unit_3_5 addPrimaryWeaponItem "acc_pointer_IR";
unit_3_5 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_3_5 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_3_5);
clearMagazineCargoGlobal (backpackContainer unit_3_5);
clearWeaponCargoGlobal (backpackContainer unit_3_5);
(backpackContainer unit_3_5) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_3_5 addItemToBackpack "SmokeShell";
unit_3_5 addItemToBackpack "SmokeShell";
unit_3_5 addItemToBackpack "SmokeShell";
unit_3_5 addItemToBackpack "SmokeShell";
unit_3_5 addItemToBackpack "rhs_mag_m67";
unit_3_5 addItemToBackpack "rhs_mag_m67";
unit_3_5 addItemToBackpack "rhs_mag_m67";
unit_3_5 addItemToBackpack "rhs_mag_m67";
unit_3_5 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_3_5);
clearMagazineCargoGlobal (vestContainer unit_3_5);
clearWeaponCargoGlobal (vestContainer unit_3_5);
(vestContainer unit_3_5) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_3_5 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_3_5);
clearMagazineCargoGlobal (uniformContainer unit_3_5);
clearWeaponCargoGlobal (uniformContainer unit_3_5);
(uniformContainer unit_3_5) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_3_5 addWeapon "tf_anprc152";
unit_3_5 selectWeapon (primaryWeapon unit_3_5);
};

if (!isNil "unit_3_6") then {
removeallweapons unit_3_6;
removeallassigneditems unit_3_6;
removeBackpack unit_3_6;
removeVest unit_3_6;
removeHeadgear unit_3_6;
removeUniform unit_3_6;
removeGoggles unit_3_6;

unit_3_6 addWeapon "ItemMap";
unit_3_6 addWeapon "ItemWatch";
unit_3_6 addWeapon "ItemCompass";
unit_3_6 addWeapon "rhsusf_ach_helmet_ocp";
unit_3_6 addWeapon "rhsusf_ANPVS_15";
unit_3_6 addWeapon "Binocular";
unit_3_6 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_3_6) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_3_6 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_3_6;
unit_3_6 addPrimaryWeaponItem "acc_pointer_IR";
unit_3_6 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_3_6 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_3_6);
clearMagazineCargoGlobal (backpackContainer unit_3_6);
clearWeaponCargoGlobal (backpackContainer unit_3_6);
unit_3_6 addItemToBackpack "SmokeShell";
unit_3_6 addItemToBackpack "SmokeShell";
unit_3_6 addItemToBackpack "SmokeShell";
unit_3_6 addItemToBackpack "SmokeShell";
unit_3_6 addItemToBackpack "rhs_mag_m67";
unit_3_6 addItemToBackpack "rhs_mag_m67";
unit_3_6 addItemToBackpack "rhs_mag_m67";
unit_3_6 addItemToBackpack "rhs_mag_m67";
unit_3_6 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_3_6);
clearMagazineCargoGlobal (vestContainer unit_3_6);
clearWeaponCargoGlobal (vestContainer unit_3_6);
(vestContainer unit_3_6) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_3_6 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_3_6);
clearMagazineCargoGlobal (uniformContainer unit_3_6);
clearWeaponCargoGlobal (uniformContainer unit_3_6);
(uniformContainer unit_3_6) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_3_6 addWeapon "tf_anprc152";
unit_3_6 selectWeapon (primaryWeapon unit_3_6);
};

if (!isNil "unit_4_7") then {
removeallweapons unit_4_7;
removeallassigneditems unit_4_7;
removeBackpack unit_4_7;
removeVest unit_4_7;
removeHeadgear unit_4_7;
removeUniform unit_4_7;
removeGoggles unit_4_7;

unit_4_7 addWeapon "ItemMap";
unit_4_7 addWeapon "ItemWatch";
unit_4_7 addWeapon "ItemCompass";
unit_4_7 addWeapon "rhsusf_ach_helmet_ocp";
unit_4_7 addWeapon "rhsusf_ANPVS_15";
unit_4_7 addWeapon "Binocular";
unit_4_7 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_4_7) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_4_7 addWeapon "rhs_m4a1_m320";
removeBackpack unit_4_7;
unit_4_7 addPrimaryWeaponItem "acc_pointer_IR";
unit_4_7 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_4_7 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_4_7);
clearMagazineCargoGlobal (backpackContainer unit_4_7);
clearWeaponCargoGlobal (backpackContainer unit_4_7);
(backpackContainer unit_4_7) addmagazinecargoGlobal ["3Rnd_SmokeGreen_Grenade_shell",2];
(backpackContainer unit_4_7) addmagazinecargoGlobal ["3Rnd_SmokeRed_Grenade_shell",2];
(backpackContainer unit_4_7) addmagazinecargoGlobal ["3Rnd_SmokeBlue_Grenade_shell",2];
unit_4_7 addItemToBackpack "SmokeShell";
unit_4_7 addItemToBackpack "SmokeShell";
unit_4_7 addItemToBackpack "SmokeShell";
unit_4_7 addItemToBackpack "SmokeShell";
unit_4_7 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_4_7);
clearMagazineCargoGlobal (vestContainer unit_4_7);
clearWeaponCargoGlobal (vestContainer unit_4_7);
(vestContainer unit_4_7) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_4_7 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_4_7);
clearMagazineCargoGlobal (uniformContainer unit_4_7);
clearWeaponCargoGlobal (uniformContainer unit_4_7);
(uniformContainer unit_4_7) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_4_7 addWeapon "tf_anprc152";
unit_4_7 selectWeapon (primaryWeapon unit_4_7);
};

if (!isNil "unit_4_8") then {
removeallweapons unit_4_8;
removeallassigneditems unit_4_8;
removeBackpack unit_4_8;
removeVest unit_4_8;
removeHeadgear unit_4_8;
removeUniform unit_4_8;
removeGoggles unit_4_8;

unit_4_8 addWeapon "ItemMap";
unit_4_8 addWeapon "ItemWatch";
unit_4_8 addWeapon "ItemCompass";
unit_4_8 addWeapon "rhsusf_ach_helmet_ocp";
unit_4_8 addWeapon "rhsusf_ANPVS_15";
unit_4_8 addWeapon "Binocular";
unit_4_8 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_4_8) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_4_8 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_4_8;
unit_4_8 addPrimaryWeaponItem "acc_pointer_IR";
unit_4_8 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_4_8 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_4_8) addmagazinecargoGlobal ["rhs_fgm148_magazine_AT",1];
unit_4_8 addWeapon "rhs_weap_fgm148";
removeBackpack unit_4_8;
unit_4_8 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_4_8);
clearMagazineCargoGlobal (backpackContainer unit_4_8);
clearWeaponCargoGlobal (backpackContainer unit_4_8);
(backpackContainer unit_4_8) addmagazinecargoGlobal ["rhs_fgm148_magazine_AT",2];
unit_4_8 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_4_8);
clearMagazineCargoGlobal (vestContainer unit_4_8);
clearWeaponCargoGlobal (vestContainer unit_4_8);
(vestContainer unit_4_8) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_4_8 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_4_8);
clearMagazineCargoGlobal (uniformContainer unit_4_8);
clearWeaponCargoGlobal (uniformContainer unit_4_8);
(uniformContainer unit_4_8) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_4_8 addWeapon "tf_anprc152";
unit_4_8 selectWeapon (primaryWeapon unit_4_8);
};

if (!isNil "unit_4_9") then {
removeallweapons unit_4_9;
removeallassigneditems unit_4_9;
removeBackpack unit_4_9;
removeVest unit_4_9;
removeHeadgear unit_4_9;
removeUniform unit_4_9;
removeGoggles unit_4_9;

unit_4_9 addWeapon "ItemMap";
unit_4_9 addWeapon "ItemWatch";
unit_4_9 addWeapon "ItemCompass";
unit_4_9 addWeapon "rhsusf_ach_helmet_ocp";
unit_4_9 addWeapon "rhsusf_ANPVS_15";
unit_4_9 addWeapon "Binocular";
unit_4_9 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_4_9) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_4_9 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_4_9;
unit_4_9 addPrimaryWeaponItem "acc_pointer_IR";
unit_4_9 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_4_9 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_4_9);
clearMagazineCargoGlobal (backpackContainer unit_4_9);
clearWeaponCargoGlobal (backpackContainer unit_4_9);
(backpackContainer unit_4_9) addmagazinecargoGlobal ["rhs_fgm148_magazine_AT",2];
unit_4_9 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_4_9);
clearMagazineCargoGlobal (vestContainer unit_4_9);
clearWeaponCargoGlobal (vestContainer unit_4_9);
(vestContainer unit_4_9) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_4_9 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_4_9);
clearMagazineCargoGlobal (uniformContainer unit_4_9);
clearWeaponCargoGlobal (uniformContainer unit_4_9);
(uniformContainer unit_4_9) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_4_9 addWeapon "tf_anprc152";
unit_4_9 selectWeapon (primaryWeapon unit_4_9);
};

if (!isNil "unit_4_10") then {
removeallweapons unit_4_10;
removeallassigneditems unit_4_10;
removeBackpack unit_4_10;
removeVest unit_4_10;
removeHeadgear unit_4_10;
removeUniform unit_4_10;
removeGoggles unit_4_10;

unit_4_10 addWeapon "ItemMap";
unit_4_10 addWeapon "ItemWatch";
unit_4_10 addWeapon "ItemCompass";
unit_4_10 addWeapon "rhsusf_ach_helmet_ocp";
unit_4_10 addWeapon "rhsusf_ANPVS_15";
unit_4_10 addWeapon "Binocular";
unit_4_10 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_4_10) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_4_10 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_4_10;
unit_4_10 addPrimaryWeaponItem "acc_pointer_IR";
unit_4_10 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_4_10 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_4_10);
clearMagazineCargoGlobal (backpackContainer unit_4_10);
clearWeaponCargoGlobal (backpackContainer unit_4_10);
unit_4_10 addItemToBackpack "SmokeShell";
unit_4_10 addItemToBackpack "SmokeShell";
unit_4_10 addItemToBackpack "SmokeShell";
unit_4_10 addItemToBackpack "SmokeShell";
unit_4_10 addItemToBackpack "rhs_mag_m67";
unit_4_10 addItemToBackpack "rhs_mag_m67";
unit_4_10 addItemToBackpack "rhs_mag_m67";
unit_4_10 addItemToBackpack "rhs_mag_m67";
unit_4_10 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_4_10);
clearMagazineCargoGlobal (vestContainer unit_4_10);
clearWeaponCargoGlobal (vestContainer unit_4_10);
(vestContainer unit_4_10) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_4_10 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_4_10);
clearMagazineCargoGlobal (uniformContainer unit_4_10);
clearWeaponCargoGlobal (uniformContainer unit_4_10);
(uniformContainer unit_4_10) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_4_10 addWeapon "tf_anprc152";
unit_4_10 selectWeapon (primaryWeapon unit_4_10);
};

if (!isNil "AAVPunit") then {
removeallweapons AAVPunit;
removeallassigneditems AAVPunit;
removeBackpack AAVPunit;
removeVest AAVPunit;
removeHeadgear AAVPunit;
removeUniform AAVPunit;
removeGoggles AAVPunit;

if (count weapons AAVPunit > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons AAVPunit) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     AAVPunit selectWeapon (_muzzles select 0);
  }
  else {
     AAVPunit selectWeapon _type;
  };
};
};

if (!isNil "unit_59_175") then {
removeallweapons unit_59_175;
removeallassigneditems unit_59_175;
removeBackpack unit_59_175;
removeVest unit_59_175;
removeHeadgear unit_59_175;
removeUniform unit_59_175;
removeGoggles unit_59_175;

if (count weapons unit_59_175 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons unit_59_175) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     unit_59_175 selectWeapon (_muzzles select 0);
  }
  else {
     unit_59_175 selectWeapon _type;
  };
};
};

if (!isNil "unit_59_176") then {
removeallweapons unit_59_176;
removeallassigneditems unit_59_176;
removeBackpack unit_59_176;
removeVest unit_59_176;
removeHeadgear unit_59_176;
removeUniform unit_59_176;
removeGoggles unit_59_176;

if (count weapons unit_59_176 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons unit_59_176) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     unit_59_176 selectWeapon (_muzzles select 0);
  }
  else {
     unit_59_176 selectWeapon _type;
  };
};
};

if (!isNil "unit_59_177") then {
removeallweapons unit_59_177;
removeallassigneditems unit_59_177;
removeBackpack unit_59_177;
removeVest unit_59_177;
removeHeadgear unit_59_177;
removeUniform unit_59_177;
removeGoggles unit_59_177;

if (count weapons unit_59_177 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons unit_59_177) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     unit_59_177 selectWeapon (_muzzles select 0);
  }
  else {
     unit_59_177 selectWeapon _type;
  };
};
};

if (!isNil "unit_59_178") then {
removeallweapons unit_59_178;
removeallassigneditems unit_59_178;
removeBackpack unit_59_178;
removeVest unit_59_178;
removeHeadgear unit_59_178;
removeUniform unit_59_178;
removeGoggles unit_59_178;

if (count weapons unit_59_178 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons unit_59_178) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     unit_59_178 selectWeapon (_muzzles select 0);
  }
  else {
     unit_59_178 selectWeapon _type;
  };
};
};

if (!isNil "unit_59_179") then {
removeallweapons unit_59_179;
removeallassigneditems unit_59_179;
removeBackpack unit_59_179;
removeVest unit_59_179;
removeHeadgear unit_59_179;
removeUniform unit_59_179;
removeGoggles unit_59_179;

if (count weapons unit_59_179 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons unit_59_179) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     unit_59_179 selectWeapon (_muzzles select 0);
  }
  else {
     unit_59_179 selectWeapon _type;
  };
};
};

if (!isNil "unit_59_180") then {
removeallweapons unit_59_180;
removeallassigneditems unit_59_180;
removeBackpack unit_59_180;
removeVest unit_59_180;
removeHeadgear unit_59_180;
removeUniform unit_59_180;
removeGoggles unit_59_180;

if (count weapons unit_59_180 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons unit_59_180) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     unit_59_180 selectWeapon (_muzzles select 0);
  }
  else {
     unit_59_180 selectWeapon _type;
  };
};
};

if (!isNil "unit_59_181") then {
removeallweapons unit_59_181;
removeallassigneditems unit_59_181;
removeBackpack unit_59_181;
removeVest unit_59_181;
removeHeadgear unit_59_181;
removeUniform unit_59_181;
removeGoggles unit_59_181;

if (count weapons unit_59_181 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons unit_59_181) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     unit_59_181 selectWeapon (_muzzles select 0);
  }
  else {
     unit_59_181 selectWeapon _type;
  };
};
};

if (!isNil "unit_59_182") then {
removeallweapons unit_59_182;
removeallassigneditems unit_59_182;
removeBackpack unit_59_182;
removeVest unit_59_182;
removeHeadgear unit_59_182;
removeUniform unit_59_182;
removeGoggles unit_59_182;

if (count weapons unit_59_182 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons unit_59_182) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     unit_59_182 selectWeapon (_muzzles select 0);
  }
  else {
     unit_59_182 selectWeapon _type;
  };
};
};

if (!isNil "unit_59_183") then {
removeallweapons unit_59_183;
removeallassigneditems unit_59_183;
removeBackpack unit_59_183;
removeVest unit_59_183;
removeHeadgear unit_59_183;
removeUniform unit_59_183;
removeGoggles unit_59_183;

if (count weapons unit_59_183 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons unit_59_183) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     unit_59_183 selectWeapon (_muzzles select 0);
  }
  else {
     unit_59_183 selectWeapon _type;
  };
};
};

