/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Sat Feb 14 11:19:13 JST 2015
* Mission file name: RHS_CO08_Borrowed_Scenery_1_3.Altis
* Mission name: RHS_CO08_Borrowed_Scenery_1_3.Altis
* Required mods:
* + ArmA 3
* + RHS USAF
* + TFAR
* 
* Call the script: _dummy = [] execvm "lea\loadoutServer.sqf";
* 
*/

/**
* Loadout for crates
*/

//No named crates in this mission.

/**
* Loadout for soldiers units
*/

if (!isNil "unit_22_37") then {
removeallweapons unit_22_37;
removeallassigneditems unit_22_37;
removeBackpack unit_22_37;
removeVest unit_22_37;
removeHeadgear unit_22_37;
removeUniform unit_22_37;
removeGoggles unit_22_37;

unit_22_37 addWeapon "ItemMap";
unit_22_37 addWeapon "ItemWatch";
unit_22_37 addWeapon "ItemCompass";
unit_22_37 addWeapon "rhsusf_ach_helmet_ocp";
unit_22_37 addWeapon "rhsusf_ANPVS_15";
unit_22_37 addWeapon "Binocular";
unit_22_37 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_22_37) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_22_37 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_22_37;
unit_22_37 addPrimaryWeaponItem "acc_pointer_IR";
unit_22_37 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_22_37 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_22_37);
clearMagazineCargoGlobal (backpackContainer unit_22_37);
clearWeaponCargoGlobal (backpackContainer unit_22_37);
unit_22_37 addItemToBackpack "SmokeShell";
unit_22_37 addItemToBackpack "SmokeShell";
unit_22_37 addItemToBackpack "SmokeShell";
unit_22_37 addItemToBackpack "SmokeShell";
unit_22_37 addItemToBackpack "rhs_mag_m67";
unit_22_37 addItemToBackpack "rhs_mag_m67";
unit_22_37 addItemToBackpack "rhs_mag_m67";
unit_22_37 addItemToBackpack "rhs_mag_m67";
unit_22_37 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_22_37);
clearMagazineCargoGlobal (vestContainer unit_22_37);
clearWeaponCargoGlobal (vestContainer unit_22_37);
(vestContainer unit_22_37) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_22_37 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_22_37);
clearMagazineCargoGlobal (uniformContainer unit_22_37);
clearWeaponCargoGlobal (uniformContainer unit_22_37);
(uniformContainer unit_22_37) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_22_37 addWeapon "tf_anprc152";
unit_22_37 selectWeapon (primaryWeapon unit_22_37);
};

if (!isNil "unit_22_38") then {
removeallweapons unit_22_38;
removeallassigneditems unit_22_38;
removeBackpack unit_22_38;
removeVest unit_22_38;
removeHeadgear unit_22_38;
removeUniform unit_22_38;
removeGoggles unit_22_38;

unit_22_38 addWeapon "ItemMap";
unit_22_38 addWeapon "ItemWatch";
unit_22_38 addWeapon "ItemCompass";
unit_22_38 addWeapon "rhsusf_ach_helmet_ocp";
unit_22_38 addWeapon "rhsusf_ANPVS_15";
unit_22_38 addWeapon "Binocular";
unit_22_38 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_22_38) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_22_38 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_22_38;
unit_22_38 addPrimaryWeaponItem "acc_pointer_IR";
unit_22_38 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_22_38 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_22_38);
clearMagazineCargoGlobal (backpackContainer unit_22_38);
clearWeaponCargoGlobal (backpackContainer unit_22_38);
unit_22_38 addItemToBackpack "SmokeShell";
unit_22_38 addItemToBackpack "SmokeShell";
unit_22_38 addItemToBackpack "SmokeShell";
unit_22_38 addItemToBackpack "SmokeShell";
unit_22_38 addItemToBackpack "rhs_mag_m67";
unit_22_38 addItemToBackpack "rhs_mag_m67";
unit_22_38 addItemToBackpack "rhs_mag_m67";
unit_22_38 addItemToBackpack "rhs_mag_m67";
unit_22_38 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_22_38);
clearMagazineCargoGlobal (vestContainer unit_22_38);
clearWeaponCargoGlobal (vestContainer unit_22_38);
(vestContainer unit_22_38) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_22_38 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_22_38);
clearMagazineCargoGlobal (uniformContainer unit_22_38);
clearWeaponCargoGlobal (uniformContainer unit_22_38);
(uniformContainer unit_22_38) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_22_38 addWeapon "tf_anprc152";
unit_22_38 selectWeapon (primaryWeapon unit_22_38);
};

if (!isNil "unit_22_39") then {
removeallweapons unit_22_39;
removeallassigneditems unit_22_39;
removeBackpack unit_22_39;
removeVest unit_22_39;
removeHeadgear unit_22_39;
removeUniform unit_22_39;
removeGoggles unit_22_39;

unit_22_39 addWeapon "ItemMap";
unit_22_39 addWeapon "ItemWatch";
unit_22_39 addWeapon "ItemCompass";
unit_22_39 addWeapon "rhsusf_ach_helmet_ocp";
unit_22_39 addWeapon "rhsusf_ANPVS_15";
unit_22_39 addWeapon "Binocular";
unit_22_39 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_22_39) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_22_39 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_22_39;
unit_22_39 addPrimaryWeaponItem "acc_pointer_IR";
unit_22_39 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_22_39 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_22_39);
clearMagazineCargoGlobal (backpackContainer unit_22_39);
clearWeaponCargoGlobal (backpackContainer unit_22_39);
unit_22_39 addItemToBackpack "SmokeShell";
unit_22_39 addItemToBackpack "SmokeShell";
unit_22_39 addItemToBackpack "SmokeShell";
unit_22_39 addItemToBackpack "SmokeShell";
unit_22_39 addItemToBackpack "rhs_mag_m67";
unit_22_39 addItemToBackpack "rhs_mag_m67";
unit_22_39 addItemToBackpack "rhs_mag_m67";
unit_22_39 addItemToBackpack "rhs_mag_m67";
unit_22_39 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_22_39);
clearMagazineCargoGlobal (vestContainer unit_22_39);
clearWeaponCargoGlobal (vestContainer unit_22_39);
(vestContainer unit_22_39) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_22_39 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_22_39);
clearMagazineCargoGlobal (uniformContainer unit_22_39);
clearWeaponCargoGlobal (uniformContainer unit_22_39);
(uniformContainer unit_22_39) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_22_39 addWeapon "tf_anprc152";
unit_22_39 selectWeapon (primaryWeapon unit_22_39);
};

if (!isNil "unit_22_40") then {
removeallweapons unit_22_40;
removeallassigneditems unit_22_40;
removeBackpack unit_22_40;
removeVest unit_22_40;
removeHeadgear unit_22_40;
removeUniform unit_22_40;
removeGoggles unit_22_40;

unit_22_40 addWeapon "ItemMap";
unit_22_40 addWeapon "ItemWatch";
unit_22_40 addWeapon "ItemCompass";
unit_22_40 addWeapon "rhsusf_ach_helmet_ocp";
unit_22_40 addWeapon "rhsusf_ANPVS_15";
unit_22_40 addWeapon "Binocular";
unit_22_40 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_22_40) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_22_40 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_22_40;
unit_22_40 addPrimaryWeaponItem "acc_pointer_IR";
unit_22_40 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_22_40 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_22_40);
clearMagazineCargoGlobal (backpackContainer unit_22_40);
clearWeaponCargoGlobal (backpackContainer unit_22_40);
unit_22_40 addItemToBackpack "SmokeShell";
unit_22_40 addItemToBackpack "SmokeShell";
unit_22_40 addItemToBackpack "SmokeShell";
unit_22_40 addItemToBackpack "SmokeShell";
unit_22_40 addItemToBackpack "rhs_mag_m67";
unit_22_40 addItemToBackpack "rhs_mag_m67";
unit_22_40 addItemToBackpack "rhs_mag_m67";
unit_22_40 addItemToBackpack "rhs_mag_m67";
unit_22_40 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_22_40);
clearMagazineCargoGlobal (vestContainer unit_22_40);
clearWeaponCargoGlobal (vestContainer unit_22_40);
(vestContainer unit_22_40) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_22_40 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_22_40);
clearMagazineCargoGlobal (uniformContainer unit_22_40);
clearWeaponCargoGlobal (uniformContainer unit_22_40);
(uniformContainer unit_22_40) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_22_40 addWeapon "tf_anprc152";
unit_22_40 selectWeapon (primaryWeapon unit_22_40);
};

if (!isNil "unit_23_41") then {
removeallweapons unit_23_41;
removeallassigneditems unit_23_41;
removeBackpack unit_23_41;
removeVest unit_23_41;
removeHeadgear unit_23_41;
removeUniform unit_23_41;
removeGoggles unit_23_41;

unit_23_41 addWeapon "ItemMap";
unit_23_41 addWeapon "ItemWatch";
unit_23_41 addWeapon "ItemCompass";
unit_23_41 addWeapon "rhsusf_ach_helmet_ocp";
unit_23_41 addWeapon "rhsusf_ANPVS_15";
unit_23_41 addWeapon "Binocular";
unit_23_41 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_23_41) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_23_41 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_23_41;
unit_23_41 addPrimaryWeaponItem "acc_pointer_IR";
unit_23_41 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_23_41 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_23_41);
clearMagazineCargoGlobal (backpackContainer unit_23_41);
clearWeaponCargoGlobal (backpackContainer unit_23_41);
unit_23_41 addItemToBackpack "SmokeShell";
unit_23_41 addItemToBackpack "SmokeShell";
unit_23_41 addItemToBackpack "SmokeShell";
unit_23_41 addItemToBackpack "SmokeShell";
unit_23_41 addItemToBackpack "rhs_mag_m67";
unit_23_41 addItemToBackpack "rhs_mag_m67";
unit_23_41 addItemToBackpack "rhs_mag_m67";
unit_23_41 addItemToBackpack "rhs_mag_m67";
unit_23_41 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_23_41);
clearMagazineCargoGlobal (vestContainer unit_23_41);
clearWeaponCargoGlobal (vestContainer unit_23_41);
(vestContainer unit_23_41) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_23_41 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_23_41);
clearMagazineCargoGlobal (uniformContainer unit_23_41);
clearWeaponCargoGlobal (uniformContainer unit_23_41);
(uniformContainer unit_23_41) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_23_41 addWeapon "tf_anprc152";
unit_23_41 selectWeapon (primaryWeapon unit_23_41);
};

if (!isNil "unit_23_42") then {
removeallweapons unit_23_42;
removeallassigneditems unit_23_42;
removeBackpack unit_23_42;
removeVest unit_23_42;
removeHeadgear unit_23_42;
removeUniform unit_23_42;
removeGoggles unit_23_42;

unit_23_42 addWeapon "ItemMap";
unit_23_42 addWeapon "ItemWatch";
unit_23_42 addWeapon "ItemCompass";
unit_23_42 addWeapon "rhsusf_ach_helmet_ocp";
unit_23_42 addWeapon "rhsusf_ANPVS_15";
unit_23_42 addWeapon "Binocular";
unit_23_42 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_23_42) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_23_42 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_23_42;
unit_23_42 addPrimaryWeaponItem "acc_pointer_IR";
unit_23_42 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_23_42 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_23_42);
clearMagazineCargoGlobal (backpackContainer unit_23_42);
clearWeaponCargoGlobal (backpackContainer unit_23_42);
unit_23_42 addItemToBackpack "SmokeShell";
unit_23_42 addItemToBackpack "SmokeShell";
unit_23_42 addItemToBackpack "SmokeShell";
unit_23_42 addItemToBackpack "SmokeShell";
unit_23_42 addItemToBackpack "rhs_mag_m67";
unit_23_42 addItemToBackpack "rhs_mag_m67";
unit_23_42 addItemToBackpack "rhs_mag_m67";
unit_23_42 addItemToBackpack "rhs_mag_m67";
unit_23_42 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_23_42);
clearMagazineCargoGlobal (vestContainer unit_23_42);
clearWeaponCargoGlobal (vestContainer unit_23_42);
(vestContainer unit_23_42) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_23_42 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_23_42);
clearMagazineCargoGlobal (uniformContainer unit_23_42);
clearWeaponCargoGlobal (uniformContainer unit_23_42);
(uniformContainer unit_23_42) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_23_42 addWeapon "tf_anprc152";
unit_23_42 selectWeapon (primaryWeapon unit_23_42);
};

if (!isNil "unit_23_43") then {
removeallweapons unit_23_43;
removeallassigneditems unit_23_43;
removeBackpack unit_23_43;
removeVest unit_23_43;
removeHeadgear unit_23_43;
removeUniform unit_23_43;
removeGoggles unit_23_43;

unit_23_43 addWeapon "ItemMap";
unit_23_43 addWeapon "ItemWatch";
unit_23_43 addWeapon "ItemCompass";
unit_23_43 addWeapon "rhsusf_ach_helmet_ocp";
unit_23_43 addWeapon "rhsusf_ANPVS_15";
unit_23_43 addWeapon "Binocular";
unit_23_43 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_23_43) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_23_43 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_23_43;
unit_23_43 addPrimaryWeaponItem "acc_pointer_IR";
unit_23_43 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_23_43 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_23_43);
clearMagazineCargoGlobal (backpackContainer unit_23_43);
clearWeaponCargoGlobal (backpackContainer unit_23_43);
unit_23_43 addItemToBackpack "SmokeShell";
unit_23_43 addItemToBackpack "SmokeShell";
unit_23_43 addItemToBackpack "SmokeShell";
unit_23_43 addItemToBackpack "SmokeShell";
unit_23_43 addItemToBackpack "rhs_mag_m67";
unit_23_43 addItemToBackpack "rhs_mag_m67";
unit_23_43 addItemToBackpack "rhs_mag_m67";
unit_23_43 addItemToBackpack "rhs_mag_m67";
unit_23_43 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_23_43);
clearMagazineCargoGlobal (vestContainer unit_23_43);
clearWeaponCargoGlobal (vestContainer unit_23_43);
(vestContainer unit_23_43) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_23_43 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_23_43);
clearMagazineCargoGlobal (uniformContainer unit_23_43);
clearWeaponCargoGlobal (uniformContainer unit_23_43);
(uniformContainer unit_23_43) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_23_43 addWeapon "tf_anprc152";
unit_23_43 selectWeapon (primaryWeapon unit_23_43);
};

if (!isNil "unit_23_44") then {
removeallweapons unit_23_44;
removeallassigneditems unit_23_44;
removeBackpack unit_23_44;
removeVest unit_23_44;
removeHeadgear unit_23_44;
removeUniform unit_23_44;
removeGoggles unit_23_44;

unit_23_44 addWeapon "ItemMap";
unit_23_44 addWeapon "ItemWatch";
unit_23_44 addWeapon "ItemCompass";
unit_23_44 addWeapon "rhsusf_ach_helmet_ocp";
unit_23_44 addWeapon "rhsusf_ANPVS_15";
unit_23_44 addWeapon "Binocular";
unit_23_44 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_23_44) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_23_44 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_23_44;
unit_23_44 addPrimaryWeaponItem "acc_pointer_IR";
unit_23_44 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_23_44 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_23_44);
clearMagazineCargoGlobal (backpackContainer unit_23_44);
clearWeaponCargoGlobal (backpackContainer unit_23_44);
unit_23_44 addItemToBackpack "SmokeShell";
unit_23_44 addItemToBackpack "SmokeShell";
unit_23_44 addItemToBackpack "SmokeShell";
unit_23_44 addItemToBackpack "SmokeShell";
unit_23_44 addItemToBackpack "rhs_mag_m67";
unit_23_44 addItemToBackpack "rhs_mag_m67";
unit_23_44 addItemToBackpack "rhs_mag_m67";
unit_23_44 addItemToBackpack "rhs_mag_m67";
unit_23_44 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_23_44);
clearMagazineCargoGlobal (vestContainer unit_23_44);
clearWeaponCargoGlobal (vestContainer unit_23_44);
(vestContainer unit_23_44) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_23_44 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_23_44);
clearMagazineCargoGlobal (uniformContainer unit_23_44);
clearWeaponCargoGlobal (uniformContainer unit_23_44);
(uniformContainer unit_23_44) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_23_44 addWeapon "tf_anprc152";
unit_23_44 selectWeapon (primaryWeapon unit_23_44);
};

