/**
* Generated by LEA for Arma 3
* Version: 2.0.24
* Mon Jan 08 20:14:16 JST 2018
* 
* Call the script: _dummy = this execvm "supply_launcher.sqf";
* 
*/

if (isServer) then {
  clearweaponcargoGlobal _this;
  clearmagazinecargoGlobal _this;
  clearitemcargoGlobal _this;

//  _this addweaponcargoGlobal ["CUP_launch_M47",1];
  _this addweaponcargoGlobal ["CUP_launch_Metis",1];
  _this addmagazinecargoGlobal ["CUP_PG7VR_M",5];
  _this addmagazinecargoGlobal ["CUP_PG7VL_M",10];
  _this addmagazinecargoGlobal ["CUP_OG7_M",10];
//  _this addmagazinecargoGlobal ["CUP_Dragon_EP1_M",2];
_this addmagazinecargoGlobal ["CUP_AT13_M",2];
  _this addmagazinecargoGlobal ["CUP_IED_V2_M",3];
};
