/**
* Generated by LEA for Arma 3
* Version: 2.0.24
* Mon Jan 08 20:06:59 JST 2018
* 
* Call the script: _dummy = this execvm "supply_medical.sqf";
* 
*/

if (isServer) then {
  clearweaponcargoGlobal _this;
  clearmagazinecargoGlobal _this;
  clearitemcargoGlobal _this;

//  _this additemcargoGlobal ["ACE_plasmaIV_250",20];
//  _this additemcargoGlobal ["ACE_plasmaIV",20];
//  _this additemcargoGlobal ["ACE_salineIV_250",20];
//  _this additemcargoGlobal ["ACE_salineIV",20];
//  _this additemcargoGlobal ["ACE_packingBandage",50];
//  _this additemcargoGlobal ["ACE_fieldDressing",50];
//  _this additemcargoGlobal ["ACE_bloodIV",20];
//  _this additemcargoGlobal ["ACE_bloodIV_250",20];


  _this additemcargoGlobal ["ACE_bloodIV_500",20];
  _this additemcargoGlobal ["ACE_morphine",60];
  _this additemcargoGlobal ["ACE_elasticBandage",70];
  _this additemcargoGlobal ["ACE_tourniquet",10];
  _this additemcargoGlobal ["ACE_epinephrine",60];
  _this additemcargoGlobal ["ACE_quikclot",50];
  _this additemcargoGlobal ["ACE_personalAidKit",20];
  _this additemcargoGlobal ["ACE_bodyBag",10];
  _this additemcargoGlobal ["ACE_surgicalKit",1];
  _this additemcargoGlobal ["adv_aceSplint_splint",50];//’Ç‰ÁMOD  ADV - ACE Splint
  _this additemcargoGlobal ["adv_aceCPR_AED",1];//’Ç‰ÁMOD  ADV - ACE CPR
  _this additemcargoGlobal ["FSGm_ItemMedicBag",1];//’Ç‰ÁMOD
};
