/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Sat Feb 14 11:26:44 JST 2015
* Mission file name: RHS_CO09_Prometheus_Inbound_1_3.Stratis
* Mission name: RHS_CO09_Prometheus_Inbound_1_3.Stratis
* Required mods:
* + ArmA 3
* + RHS USAF
* + TFAR
* 
* Call the script: _dummy = [] execvm "lea\loadoutMultiplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

//No named crates in this mission.

/**
* Loadout for soldiers units
*/

if (!isNil "unit_0_0") then {
	if (player == unit_0_0) exitwith {
removeallweapons unit_0_0;
removeallassigneditems unit_0_0;
removeBackpack unit_0_0;
removeVest unit_0_0;
removeHeadgear unit_0_0;
removeUniform unit_0_0;
removeGoggles unit_0_0;

unit_0_0 addWeapon "ItemMap";
unit_0_0 addWeapon "ItemWatch";
unit_0_0 addWeapon "ItemCompass";
unit_0_0 addWeapon "rhsusf_ach_helmet_ocp";
unit_0_0 addWeapon "rhsusf_ANPVS_15";
unit_0_0 addWeapon "Binocular";
unit_0_0 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_0_0) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_0_0 addWeapon "rhs_m4a1_m320";
removeBackpack unit_0_0;
unit_0_0 addPrimaryWeaponItem "acc_pointer_IR";
unit_0_0 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_0_0 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_0_0);
clearMagazineCargoGlobal (backpackContainer unit_0_0);
clearWeaponCargoGlobal (backpackContainer unit_0_0);
(backpackContainer unit_0_0) addmagazinecargoGlobal ["3Rnd_SmokeGreen_Grenade_shell",2];
(backpackContainer unit_0_0) addmagazinecargoGlobal ["3Rnd_SmokeRed_Grenade_shell",2];
(backpackContainer unit_0_0) addmagazinecargoGlobal ["3Rnd_SmokeBlue_Grenade_shell",2];
unit_0_0 addItemToBackpack "SmokeShell";
unit_0_0 addItemToBackpack "SmokeShell";
unit_0_0 addItemToBackpack "SmokeShell";
unit_0_0 addItemToBackpack "SmokeShell";
unit_0_0 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_0_0);
clearMagazineCargoGlobal (vestContainer unit_0_0);
clearWeaponCargoGlobal (vestContainer unit_0_0);
(vestContainer unit_0_0) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_0_0 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_0_0);
clearMagazineCargoGlobal (uniformContainer unit_0_0);
clearWeaponCargoGlobal (uniformContainer unit_0_0);
(uniformContainer unit_0_0) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_0_0 addWeapon "tf_anprc152";
unit_0_0 selectWeapon (primaryWeapon unit_0_0);
	};
};

if (!isNil "unit_0_1") then {
	if (player == unit_0_1) exitwith {
removeallweapons unit_0_1;
removeallassigneditems unit_0_1;
removeBackpack unit_0_1;
removeVest unit_0_1;
removeHeadgear unit_0_1;
removeUniform unit_0_1;
removeGoggles unit_0_1;

unit_0_1 addWeapon "ItemMap";
unit_0_1 addWeapon "ItemWatch";
unit_0_1 addWeapon "ItemCompass";
unit_0_1 addWeapon "rhsusf_ach_helmet_ocp";
unit_0_1 addWeapon "rhsusf_ANPVS_15";
unit_0_1 addWeapon "Binocular";
unit_0_1 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_0_1) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",1];
unit_0_1 addWeapon "rhs_weap_m240B";
removeBackpack unit_0_1;
unit_0_1 addPrimaryWeaponItem "acc_pointer_IR";
unit_0_1 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_0_1 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_0_1);
clearMagazineCargoGlobal (backpackContainer unit_0_1);
clearWeaponCargoGlobal (backpackContainer unit_0_1);
(backpackContainer unit_0_1) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_0_1 addItemToBackpack "SmokeShell";
unit_0_1 addItemToBackpack "SmokeShell";
unit_0_1 addItemToBackpack "SmokeShell";
unit_0_1 addItemToBackpack "SmokeShell";
unit_0_1 addItemToBackpack "rhs_mag_m67";
unit_0_1 addItemToBackpack "rhs_mag_m67";
unit_0_1 addItemToBackpack "rhs_mag_m67";
unit_0_1 addItemToBackpack "rhs_mag_m67";
unit_0_1 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_0_1);
clearMagazineCargoGlobal (vestContainer unit_0_1);
clearWeaponCargoGlobal (vestContainer unit_0_1);
(vestContainer unit_0_1) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_0_1 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_0_1);
clearMagazineCargoGlobal (uniformContainer unit_0_1);
clearWeaponCargoGlobal (uniformContainer unit_0_1);
unit_0_1 addWeapon "tf_anprc152";
unit_0_1 selectWeapon (primaryWeapon unit_0_1);
	};
};

if (!isNil "unit_0_2") then {
	if (player == unit_0_2) exitwith {
removeallweapons unit_0_2;
removeallassigneditems unit_0_2;
removeBackpack unit_0_2;
removeVest unit_0_2;
removeHeadgear unit_0_2;
removeUniform unit_0_2;
removeGoggles unit_0_2;

unit_0_2 addWeapon "ItemMap";
unit_0_2 addWeapon "ItemWatch";
unit_0_2 addWeapon "ItemCompass";
unit_0_2 addWeapon "rhsusf_ach_helmet_ocp";
unit_0_2 addWeapon "rhsusf_ANPVS_15";
unit_0_2 addWeapon "Binocular";
unit_0_2 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_0_2) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_0_2 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_0_2;
unit_0_2 addPrimaryWeaponItem "acc_pointer_IR";
unit_0_2 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_0_2 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_0_2);
clearMagazineCargoGlobal (backpackContainer unit_0_2);
clearWeaponCargoGlobal (backpackContainer unit_0_2);
(backpackContainer unit_0_2) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_0_2 addItemToBackpack "SmokeShell";
unit_0_2 addItemToBackpack "SmokeShell";
unit_0_2 addItemToBackpack "SmokeShell";
unit_0_2 addItemToBackpack "SmokeShell";
unit_0_2 addItemToBackpack "rhs_mag_m67";
unit_0_2 addItemToBackpack "rhs_mag_m67";
unit_0_2 addItemToBackpack "rhs_mag_m67";
unit_0_2 addItemToBackpack "rhs_mag_m67";
unit_0_2 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_0_2);
clearMagazineCargoGlobal (vestContainer unit_0_2);
clearWeaponCargoGlobal (vestContainer unit_0_2);
(vestContainer unit_0_2) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_0_2 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_0_2);
clearMagazineCargoGlobal (uniformContainer unit_0_2);
clearWeaponCargoGlobal (uniformContainer unit_0_2);
(uniformContainer unit_0_2) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_0_2 addWeapon "tf_anprc152";
unit_0_2 selectWeapon (primaryWeapon unit_0_2);
	};
};

if (!isNil "unit_0_3") then {
	if (player == unit_0_3) exitwith {
removeallweapons unit_0_3;
removeallassigneditems unit_0_3;
removeBackpack unit_0_3;
removeVest unit_0_3;
removeHeadgear unit_0_3;
removeUniform unit_0_3;
removeGoggles unit_0_3;

unit_0_3 addWeapon "ItemMap";
unit_0_3 addWeapon "ItemWatch";
unit_0_3 addWeapon "ItemCompass";
unit_0_3 addWeapon "rhsusf_ach_helmet_ocp";
unit_0_3 addWeapon "rhsusf_ANPVS_15";
unit_0_3 addWeapon "Binocular";
unit_0_3 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_0_3) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_0_3 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_0_3;
unit_0_3 addPrimaryWeaponItem "acc_pointer_IR";
unit_0_3 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_0_3 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_0_3);
clearMagazineCargoGlobal (backpackContainer unit_0_3);
clearWeaponCargoGlobal (backpackContainer unit_0_3);
unit_0_3 addItemToBackpack "SmokeShell";
unit_0_3 addItemToBackpack "SmokeShell";
unit_0_3 addItemToBackpack "SmokeShell";
unit_0_3 addItemToBackpack "SmokeShell";
unit_0_3 addItemToBackpack "rhs_mag_m67";
unit_0_3 addItemToBackpack "rhs_mag_m67";
unit_0_3 addItemToBackpack "rhs_mag_m67";
unit_0_3 addItemToBackpack "rhs_mag_m67";
unit_0_3 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_0_3);
clearMagazineCargoGlobal (vestContainer unit_0_3);
clearWeaponCargoGlobal (vestContainer unit_0_3);
(vestContainer unit_0_3) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_0_3 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_0_3);
clearMagazineCargoGlobal (uniformContainer unit_0_3);
clearWeaponCargoGlobal (uniformContainer unit_0_3);
(uniformContainer unit_0_3) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_0_3 addWeapon "tf_anprc152";
unit_0_3 selectWeapon (primaryWeapon unit_0_3);
	};
};

if (!isNil "unit_3_12") then {
	if (player == unit_3_12) exitwith {
removeallweapons unit_3_12;
removeallassigneditems unit_3_12;
removeBackpack unit_3_12;
removeVest unit_3_12;
removeHeadgear unit_3_12;
removeUniform unit_3_12;
removeGoggles unit_3_12;

unit_3_12 addWeapon "ItemMap";
unit_3_12 addWeapon "ItemWatch";
unit_3_12 addWeapon "ItemCompass";
unit_3_12 addWeapon "rhsusf_ach_helmet_ocp";
unit_3_12 addWeapon "rhsusf_ANPVS_15";
unit_3_12 addWeapon "Binocular";
unit_3_12 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_3_12) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_3_12 addWeapon "rhs_m4a1_m320";
removeBackpack unit_3_12;
unit_3_12 addPrimaryWeaponItem "acc_pointer_IR";
unit_3_12 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_3_12 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_3_12);
clearMagazineCargoGlobal (backpackContainer unit_3_12);
clearWeaponCargoGlobal (backpackContainer unit_3_12);
(backpackContainer unit_3_12) addmagazinecargoGlobal ["3Rnd_SmokeGreen_Grenade_shell",2];
(backpackContainer unit_3_12) addmagazinecargoGlobal ["3Rnd_SmokeRed_Grenade_shell",2];
(backpackContainer unit_3_12) addmagazinecargoGlobal ["3Rnd_SmokeBlue_Grenade_shell",2];
unit_3_12 addItemToBackpack "SmokeShell";
unit_3_12 addItemToBackpack "SmokeShell";
unit_3_12 addItemToBackpack "SmokeShell";
unit_3_12 addItemToBackpack "SmokeShell";
unit_3_12 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_3_12);
clearMagazineCargoGlobal (vestContainer unit_3_12);
clearWeaponCargoGlobal (vestContainer unit_3_12);
(vestContainer unit_3_12) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_3_12 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_3_12);
clearMagazineCargoGlobal (uniformContainer unit_3_12);
clearWeaponCargoGlobal (uniformContainer unit_3_12);
(uniformContainer unit_3_12) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_3_12 addWeapon "tf_anprc152";
unit_3_12 selectWeapon (primaryWeapon unit_3_12);
	};
};

if (!isNil "unit_3_13") then {
	if (player == unit_3_13) exitwith {
removeallweapons unit_3_13;
removeallassigneditems unit_3_13;
removeBackpack unit_3_13;
removeVest unit_3_13;
removeHeadgear unit_3_13;
removeUniform unit_3_13;
removeGoggles unit_3_13;

unit_3_13 addWeapon "ItemMap";
unit_3_13 addWeapon "ItemWatch";
unit_3_13 addWeapon "ItemCompass";
unit_3_13 addWeapon "rhsusf_ach_helmet_ocp";
unit_3_13 addWeapon "rhsusf_ANPVS_15";
unit_3_13 addWeapon "Binocular";
unit_3_13 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_3_13) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",1];
unit_3_13 addWeapon "rhs_weap_m240B";
removeBackpack unit_3_13;
unit_3_13 addPrimaryWeaponItem "acc_pointer_IR";
unit_3_13 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_3_13 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_3_13);
clearMagazineCargoGlobal (backpackContainer unit_3_13);
clearWeaponCargoGlobal (backpackContainer unit_3_13);
(backpackContainer unit_3_13) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_3_13 addItemToBackpack "SmokeShell";
unit_3_13 addItemToBackpack "SmokeShell";
unit_3_13 addItemToBackpack "SmokeShell";
unit_3_13 addItemToBackpack "SmokeShell";
unit_3_13 addItemToBackpack "rhs_mag_m67";
unit_3_13 addItemToBackpack "rhs_mag_m67";
unit_3_13 addItemToBackpack "rhs_mag_m67";
unit_3_13 addItemToBackpack "rhs_mag_m67";
unit_3_13 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_3_13);
clearMagazineCargoGlobal (vestContainer unit_3_13);
clearWeaponCargoGlobal (vestContainer unit_3_13);
(vestContainer unit_3_13) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_3_13 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_3_13);
clearMagazineCargoGlobal (uniformContainer unit_3_13);
clearWeaponCargoGlobal (uniformContainer unit_3_13);
unit_3_13 addWeapon "tf_anprc152";
unit_3_13 selectWeapon (primaryWeapon unit_3_13);
	};
};

if (!isNil "unit_3_14") then {
	if (player == unit_3_14) exitwith {
removeallweapons unit_3_14;
removeallassigneditems unit_3_14;
removeBackpack unit_3_14;
removeVest unit_3_14;
removeHeadgear unit_3_14;
removeUniform unit_3_14;
removeGoggles unit_3_14;

unit_3_14 addWeapon "ItemMap";
unit_3_14 addWeapon "ItemWatch";
unit_3_14 addWeapon "ItemCompass";
unit_3_14 addWeapon "rhsusf_ach_helmet_ocp";
unit_3_14 addWeapon "rhsusf_ANPVS_15";
unit_3_14 addWeapon "Binocular";
unit_3_14 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_3_14) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_3_14 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_3_14;
unit_3_14 addPrimaryWeaponItem "acc_pointer_IR";
unit_3_14 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_3_14 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_3_14);
clearMagazineCargoGlobal (backpackContainer unit_3_14);
clearWeaponCargoGlobal (backpackContainer unit_3_14);
(backpackContainer unit_3_14) addmagazinecargoGlobal ["rhsusf_100Rnd_762x51",2];
unit_3_14 addItemToBackpack "SmokeShell";
unit_3_14 addItemToBackpack "SmokeShell";
unit_3_14 addItemToBackpack "SmokeShell";
unit_3_14 addItemToBackpack "SmokeShell";
unit_3_14 addItemToBackpack "rhs_mag_m67";
unit_3_14 addItemToBackpack "rhs_mag_m67";
unit_3_14 addItemToBackpack "rhs_mag_m67";
unit_3_14 addItemToBackpack "rhs_mag_m67";
unit_3_14 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_3_14);
clearMagazineCargoGlobal (vestContainer unit_3_14);
clearWeaponCargoGlobal (vestContainer unit_3_14);
(vestContainer unit_3_14) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_3_14 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_3_14);
clearMagazineCargoGlobal (uniformContainer unit_3_14);
clearWeaponCargoGlobal (uniformContainer unit_3_14);
(uniformContainer unit_3_14) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_3_14 addWeapon "tf_anprc152";
unit_3_14 selectWeapon (primaryWeapon unit_3_14);
	};
};

if (!isNil "unit_3_15") then {
	if (player == unit_3_15) exitwith {
removeallweapons unit_3_15;
removeallassigneditems unit_3_15;
removeBackpack unit_3_15;
removeVest unit_3_15;
removeHeadgear unit_3_15;
removeUniform unit_3_15;
removeGoggles unit_3_15;

unit_3_15 addWeapon "ItemMap";
unit_3_15 addWeapon "ItemWatch";
unit_3_15 addWeapon "ItemCompass";
unit_3_15 addWeapon "rhsusf_ach_helmet_ocp";
unit_3_15 addWeapon "rhsusf_ANPVS_15";
unit_3_15 addWeapon "Binocular";
unit_3_15 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_3_15) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_3_15 addWeapon "rhs_weap_m16a4_grip";
removeBackpack unit_3_15;
unit_3_15 addPrimaryWeaponItem "acc_pointer_IR";
unit_3_15 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_3_15 addBackpack "B_Carryall_cbr";
clearItemCargoGlobal (backpackContainer unit_3_15);
clearMagazineCargoGlobal (backpackContainer unit_3_15);
clearWeaponCargoGlobal (backpackContainer unit_3_15);
unit_3_15 addItemToBackpack "SmokeShell";
unit_3_15 addItemToBackpack "SmokeShell";
unit_3_15 addItemToBackpack "SmokeShell";
unit_3_15 addItemToBackpack "SmokeShell";
unit_3_15 addItemToBackpack "rhs_mag_m67";
unit_3_15 addItemToBackpack "rhs_mag_m67";
unit_3_15 addItemToBackpack "rhs_mag_m67";
unit_3_15 addItemToBackpack "rhs_mag_m67";
unit_3_15 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_3_15);
clearMagazineCargoGlobal (vestContainer unit_3_15);
clearWeaponCargoGlobal (vestContainer unit_3_15);
(vestContainer unit_3_15) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_3_15 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_3_15);
clearMagazineCargoGlobal (uniformContainer unit_3_15);
clearWeaponCargoGlobal (uniformContainer unit_3_15);
(uniformContainer unit_3_15) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_3_15 addWeapon "tf_anprc152";
unit_3_15 selectWeapon (primaryWeapon unit_3_15);
	};
};

if (!isNil "unit_4_16") then {
	if (player == unit_4_16) exitwith {
removeallweapons unit_4_16;
removeallassigneditems unit_4_16;
removeBackpack unit_4_16;
removeVest unit_4_16;
removeHeadgear unit_4_16;
removeUniform unit_4_16;
removeGoggles unit_4_16;

unit_4_16 addWeapon "ItemMap";
unit_4_16 addWeapon "ItemWatch";
unit_4_16 addWeapon "ItemCompass";
unit_4_16 addWeapon "rhsusf_ach_helmet_ocp";
unit_4_16 addWeapon "rhsusf_ANPVS_15";
unit_4_16 addWeapon "Binocular";
unit_4_16 addBackpack "B_TacticalPack_blk";
(backpackContainer unit_4_16) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
unit_4_16 addWeapon "rhs_m4a1_m320";
removeBackpack unit_4_16;
unit_4_16 addPrimaryWeaponItem "acc_pointer_IR";
unit_4_16 addPrimaryWeaponItem "rhsusf_acc_ACOG3";
unit_4_16 addBackpack "tf_rt1523g";
clearItemCargoGlobal (backpackContainer unit_4_16);
clearMagazineCargoGlobal (backpackContainer unit_4_16);
clearWeaponCargoGlobal (backpackContainer unit_4_16);
(backpackContainer unit_4_16) addmagazinecargoGlobal ["3Rnd_SmokeGreen_Grenade_shell",2];
(backpackContainer unit_4_16) addmagazinecargoGlobal ["3Rnd_SmokeRed_Grenade_shell",2];
(backpackContainer unit_4_16) addmagazinecargoGlobal ["3Rnd_SmokeBlue_Grenade_shell",2];
unit_4_16 addItemToBackpack "SmokeShell";
unit_4_16 addItemToBackpack "SmokeShell";
unit_4_16 addItemToBackpack "SmokeShell";
unit_4_16 addItemToBackpack "SmokeShell";
unit_4_16 addVest "rhsusf_iotv_ocp";
clearItemCargoGlobal (vestContainer unit_4_16);
clearMagazineCargoGlobal (vestContainer unit_4_16);
clearWeaponCargoGlobal (vestContainer unit_4_16);
(vestContainer unit_4_16) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",12];
unit_4_16 forceAddUniform "rhs_uniform_cu_ocp";
clearItemCargoGlobal (uniformContainer unit_4_16);
clearMagazineCargoGlobal (uniformContainer unit_4_16);
clearWeaponCargoGlobal (uniformContainer unit_4_16);
(uniformContainer unit_4_16) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",2];
unit_4_16 addWeapon "tf_anprc152";
unit_4_16 selectWeapon (primaryWeapon unit_4_16);
	};
};

